### ISSUE TITLE
$cookies is type of uknown while using i18n micro

### ISSUE THREAD

**Issue by kleinpetr** [dargmuesli/nuxt-cookie-control#235]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v22.3.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.10.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/github/kleinpetr/nuxt-cookies-i18n

run `pnpm typecheck`

### Describe the bug

Once I use i18n micro module https://nuxt.com/modules/nuxt-i18n-micro I am getting a typecheck error under the `nuxtApp().$cookies` as you can see in the reproduction

`'nuxtApp.$cookies' is of type 'unknown'` 

### Logs

```shell
node_modules/.pnpm/@dargmuesli+nuxt-cookie-control@8.4.13_magicast@0.3.5_rollup@4.24.0_webpack-sources@3.2.3_webpack@5.95.0/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieControl.vue:310:3 - error TS18046: 'nuxtApp.$cookies' is of type 'unknown'.

310   nuxtApp.$cookies.locale.value = props.locale
      ~~~~~~~~~~~~~~~~

node_modules/.pnpm/@dargmuesli+nuxt-cookie-control@8.4.13_magicast@0.3.5_rollup@4.24.0_webpack-sources@3.2.3_webpack@5.95.0/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieControl.vue:434:5 - error TS18046: 'nuxtApp.$cookies' is of type 'unknown'.

434     nuxtApp.$cookies.locale.value = locale
        ~~~~~~~~~~~~~~~~

node_modules/.pnpm/@dargmuesli+nuxt-cookie-control@8.4.13_magicast@0.3.5_rollup@4.24.0_webpack-sources@3.2.3_webpack@5.95.0/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieIframe.vue:36:9 - error TS7053: Element implicitly has an 'any' type because expression of type 'any' can't be used to index type 'Partial<Record<Locale, Partial<LocaleStrings>>>'.

36   () => moduleOptions.localeTexts[nuxtApp.$cookies.locale.value],
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@dargmuesli+nuxt-cookie-control@8.4.13_magicast@0.3.5_rollup@4.24.0_webpack-sources@3.2.3_webpack@5.95.0/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieIframe.vue:36:35 - error TS18046: 'nuxtApp.$cookies' is of type 'unknown'.

36   () => moduleOptions.localeTexts[nuxtApp.$cookies.locale.value],
```

**Comment by s00d** [comment]
When this module is enabled, something strange happens with the router, and the `next` function disappears from the hook. After checking the source code, it seems that this module doesn’t use `router` at all. I added a check in my module, and now everything seems to work fine. You can try version 1.21.4.

Honestly, I’m not entirely sure what was wrong, but it looks like I fixed it.

**Comment by dargmuesli** [comment]
@s00d if you mean this:
![image](https://github.com/user-attachments/assets/def0e464-62f4-454a-b1d3-ef58fe351347)

this also happens with `// '@dargmuesli/nuxt-cookie-control',` (disabled) I think: https://stackblitz.com/edit/github-rbx1ec-rhjgqp?file=nuxt.config.ts

**Comment by dargmuesli** [comment]
You can continue this discussion here or over at https://github.com/s00d/nuxt-i18n-micro/issues/27, I'm just closing this here for now as I don't think it's related to this module. But we can reopen of course if there is anything in need to change on this module's end :raised_hands:

**Comment by kleinpetr** [comment]
> When this module is enabled, something strange happens with the router, and the `next` function disappears from the hook. After checking the source code, it seems that this module doesn’t use `router` at all. I added a check in my module, and now everything seems to work fine. You can try version 1.21.4.
> 
> Honestly, I’m not entirely sure what was wrong, but it looks like I fixed it.
> 
> But actually, I had a different error, not with $cookies. Maybe this will help.
> 
> I checked it here:
> 
> https://stackblitz.com/edit/github-rbx1ec?file=app.vue
> 
> It seems to be working.

not sure what you mean by `It seems to be working` but the `pnmp typecheck` still not passing :thinking:

**Comment by s00d** [comment]
> @s00d if you mean this: ![image](https://private-user-images.githubusercontent.com/4778485/372975231-def0e464-62f4-454a-b1d3-ef58fe351347.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMzg5NzAsIm5iZiI6MTcyODAzODY3MCwicGF0aCI6Ii80Nzc4NDg1LzM3Mjk3NTIzMS1kZWYwZTQ2NC02MmY0LTQ1NGEtYjFkMy1lZjU4ZmUzNTEzNDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDRUMTA0NDMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDJlOGI2YmFjMjlkZGExNGIxYTQ0ZDJlZDI1Mzg3NWZjNDg0ZmVhNTZmMTU0YzhkZDc4NzRlYzZiZmViNjZmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dnBIRhdE2m7vzA5477rPdM182wOj6ucg0eoCRWfuFHE)
> 
> this also happens with `// '@dargmuesli/nuxt-cookie-control',` (disabled) I think: https://stackblitz.com/edit/github-rbx1ec-rhjgqp?file=nuxt.config.ts

https://stackblitz.com/edit/github-rbx1ec-fjwgte?file=nuxt.config.ts
Just add a pages folder; without it, the routing won’t be generated. I’ll try to fix this later.

**Comment by kleinpetr** [comment]
Hi @s00d @dargmuesli, I am facing this issue again, is there any recommendation how it could be fixed?

cookie-control: 8.5.0
i18n-micro: 1.70.0

![Image](https://github.com/user-attachments/assets/4ed09a99-c3b0-46ca-84e0-62a571836cf8)

**Comment by s00d** [comment]
https://stackblitz.com/edit/github-rbx1ec?file=package.json,app.vue

I don't see this error.

<img width="1057" alt="Image" src="https://github.com/user-attachments/assets/045a0576-459a-49b6-b810-856afca85ec9" />

**Comment by kleinpetr** [comment]
hi @s00d unfortunately I am not able to reproduce it again.. but when I update `vite` to `6.0.11` from `5.3.1` it was fixed.

**Comment by kleinpetr** [comment]
ok, but it proceeds only when I use `1.60.0` once I upgrade to 1.68 or 1.70. the issue is back..

**Comment by s00d** [comment]
> ok, but it proceeds only when I use `1.60.0` once I upgrade to 1.68 or 1.70. the issue is back.. here is the diff of pnpm.lock (left side is without tsc error) https://www.diffchecker.com/HFocePdK/

What's the point of sharing the lock file? Do you really think I’m going to dig through a 15,000-line file? That’s a waste of time. If the issue doesn’t happen in a clean project, it’s likely a dependency conflict. The best approach is to completely clear all lock files, delete `node_modules`, and reinstall everything from scratch. That should probably fix the problem. You might also need to update Nuxt—I’ve already updated their kit, and there were reports of issues with the router. Or, you can just keep using the old version if it’s working for you.

If you can provide a simple example or a reproducible case, I’ll likely be able to pinpoint the issue. Without that, there’s not much I can do.
